os:
  editCommand: "nvim"
customCommands:
  - key: "L"
    command: "git-chglog -o CHANGELOG.md"
    context: "global"
    description: "generate changelog file"
  - key: "t"
    prompts:
      - type: "input"
        title: "Insert new tag"
      - type: "input"
        title: "Tag message"
    description: "Create a new tag on latest commits on from current branch"
    context: "commits"
    command: "git tag -a {{index .PromptResponses 0}} -m '{{index .PromptResponses 1}}'"
