os:
  editCommand: "nvim"
customCommands:
  - key: "n"
    prompts:
      - type: "menu"
        title: "What kind of branch is it?"
        options:
          - name: "feature"
            description: "branch"
            value: "feature"
          - name: "hotfix"
            description: "branch"
            value: "hotfix"
          - name: "release"
            description: "branch"
            value: "release"
      - type: "input"
        title: "What is the new branch name?"
        initialValue: ""
    command: "git flow {{index .PromptResponses 0}} start {{index .PromptResponses 1}}"
    context: "localBranches"
    loadingText: "creating branch"
  - key: "t"
    prompts:
      - type: "input"
        title: "Insert new tag"
    description: "Create a new tag on latest commits on from current branch"
    context: "commits"
    command: "git tag -a {{index .PromptResponses 0}}"
